### ISSUE TITLE
Some un-spaced words in the database

### ISSUE THREAD

**Issue by hileamlakB** [Yididya/amharic_spell_corrector#2]
First of all thank you for your crawler and the database you have made available to the public. Just one quick thing I noticed while I was working with the data. Some words aren't separated by space and still hold meanings from the site which they were scrapped from like 
"ግዜሳይረፍድይህንንየቁርጥቀንኢትዮጵያዊለመታደግበያለንበትበጋራእንረባረብ
የየመንኤምባሲዎችንበያሉበትበተቃውሞማጨናነቅናእንቅልፍመንሳትእንዲሁምአለምአቀፍጫናማድረግያስፈልጋል
የመንአቶአንዳርጋቸውንለወያኔአሳልፋእንዳትሰጥናያለምንምቅድመሁኔታእንድትለቅሁሉምነጻነትናፋቂኢትዮጵያዊሁሉበጋራጥረትሊያደርግይገባል
ማሰርናማንገገላታትአለምአቀፍህግንየሚጥስህገወጥድርጊትነው
የአንባገነኑየህወሃትስርወመንግስትተቃዋሚዎችንማንምአገርበምንምአይነትሁኔታማፈን
የመንአቶአንዳርጋቸውጽጌንማገቷሌላአደገኛናበጣምአሳሳቢክስተትነው
"
I thought you might be interested to know.

**Comment by yididiyan** [comment]
Hi @hileamlakB,

Pleasure is all mine. And thank you for pointing that out. I have removed most of such lengthy non-sensical sentences.
